/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client2.glossary;

import backend.Word;
import javax.swing.JTable;

/**
 *
 * @author pierrezarebski
 */
public class GlossaryView extends javax.swing.JPanel implements  GlossaryViewSetter {

    private GlossaryViewListener listener;
    /**
     * Creates new panel GlossaryView
     */
    public GlossaryView() {
        initComponents();
        cBox_languageTwo.addItem("english");
        cBox_languageTwo.addItem("german");
    }
    
    public void  setGlossaryList(Word[] list){
        if(list.length == 0) return;
        String[][] tableData = new String[list.length][2];
        for(int i = 0 ; i < list.length; i++) {

            tableData[i][0] = list[i].getOrginal();

            tableData[i][1] = list[i].getTranslation();
        }
        String lang = list[0].getLanguage();

        table_glossaryList.setModel(new javax.swing.table.DefaultTableModel(tableData, new String[]{"Svenska", lang}));
    }
    
    public void setGlossaryViewListener(GlossaryViewListener listener){
        this.listener = listener;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        table_glossaryList = new javax.swing.JTable();
        btn_cancel = new javax.swing.JButton();
        btn_done = new javax.swing.JButton();
        btn_addWord = new javax.swing.JButton();
        btn_addLang = new javax.swing.JButton();
        txtfield_word2 = new javax.swing.JTextField();
        txtfield_word1 = new javax.swing.JTextField();
        txtfield_listname = new javax.swing.JTextField();
        cBox_languageTwo = new javax.swing.JComboBox();
        cBox_languageOne = new javax.swing.JComboBox();

        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        scrollPane.setMaximumSize(new java.awt.Dimension(500, 200));
        scrollPane.setMinimumSize(new java.awt.Dimension(500, 200));
        scrollPane.setPreferredSize(new java.awt.Dimension(500, 200));

        table_glossaryList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table_glossaryList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Svenska", "Språk 2"
            }
        ));
        table_glossaryList.setColumnSelectionAllowed(true);
        table_glossaryList.setMaximumSize(new java.awt.Dimension(500, 10000));
        table_glossaryList.setMinimumSize(new java.awt.Dimension(500, 200));
        table_glossaryList.setPreferredSize(new java.awt.Dimension(500, 173));
        table_glossaryList.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(table_glossaryList);
        table_glossaryList.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cancel.setText("Avbryt");
        btn_cancel.setMaximumSize(new java.awt.Dimension(100, 40));
        btn_cancel.setMinimumSize(new java.awt.Dimension(100, 40));
        btn_cancel.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_done.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_done.setText("Klar");
        btn_done.setMaximumSize(new java.awt.Dimension(100, 40));
        btn_done.setMinimumSize(new java.awt.Dimension(100, 40));
        btn_done.setPreferredSize(new java.awt.Dimension(100, 40));

        btn_addWord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_addWord.setText("Lägg till");
        btn_addWord.setMaximumSize(new java.awt.Dimension(100, 30));
        btn_addWord.setMinimumSize(new java.awt.Dimension(100, 30));
        btn_addWord.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_addWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addWordActionPerformed(evt);
            }
        });

        btn_addLang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_addLang.setText("Lägg till");
        btn_addLang.setMaximumSize(new java.awt.Dimension(100, 30));
        btn_addLang.setMinimumSize(new java.awt.Dimension(100, 30));
        btn_addLang.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_addLang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addLangActionPerformed(evt);
            }
        });

        txtfield_word2.setMaximumSize(new java.awt.Dimension(150, 30));
        txtfield_word2.setMinimumSize(new java.awt.Dimension(150, 30));
        txtfield_word2.setPreferredSize(new java.awt.Dimension(150, 30));

        txtfield_word1.setMaximumSize(new java.awt.Dimension(150, 30));
        txtfield_word1.setMinimumSize(new java.awt.Dimension(150, 30));
        txtfield_word1.setPreferredSize(new java.awt.Dimension(150, 30));

        txtfield_listname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtfield_listname.setForeground(new java.awt.Color(153, 153, 153));
        txtfield_listname.setText("Vad ska gloslistan heta?");
        txtfield_listname.setMaximumSize(new java.awt.Dimension(350, 30));
        txtfield_listname.setMinimumSize(new java.awt.Dimension(350, 30));
        txtfield_listname.setPreferredSize(new java.awt.Dimension(350, 30));
        txtfield_listname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfield_listnameMouseClicked(evt);
            }
        });

        cBox_languageTwo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cBox_languageTwo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Språk 2-" }));
        cBox_languageTwo.setMaximumSize(new java.awt.Dimension(150, 40));
        cBox_languageTwo.setMinimumSize(new java.awt.Dimension(150, 40));
        cBox_languageTwo.setPreferredSize(new java.awt.Dimension(150, 40));
        cBox_languageTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBox_languageTwoActionPerformed(evt);
            }
        });

        cBox_languageOne.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cBox_languageOne.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Svenska" }));
        cBox_languageOne.setMaximumSize(new java.awt.Dimension(150, 40));
        cBox_languageOne.setMinimumSize(new java.awt.Dimension(150, 40));
        cBox_languageOne.setPreferredSize(new java.awt.Dimension(150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfield_word1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cBox_languageOne, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(btn_done, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtfield_word2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_addWord, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cBox_languageTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(149, 149, 149))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtfield_listname, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btn_addLang, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfield_listname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBox_languageOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBox_languageTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfield_word2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfield_word1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_done, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addWordActionPerformed
        listener.newWord(txtfield_word1.getText(), txtfield_word2.getText(), (String) cBox_languageTwo.getSelectedItem());
        
        txtfield_word1.setText("");
        txtfield_word2.setText("");
    }//GEN-LAST:event_btn_addWordActionPerformed

    private void btn_addLangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addLangActionPerformed
       String language =  txtfield_listname.getText();
       
       cBox_languageTwo.addItem(language);
       cBox_languageTwo.setSelectedItem(language);
       
    }//GEN-LAST:event_btn_addLangActionPerformed

    private void txtfield_listnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfield_listnameMouseClicked
        txtfield_listname.setText("");
    }//GEN-LAST:event_txtfield_listnameMouseClicked

    private void cBox_languageTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBox_languageTwoActionPerformed
        listener.langSelected((String) cBox_languageTwo.getSelectedItem());
    }//GEN-LAST:event_cBox_languageTwoActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addLang;
    private javax.swing.JButton btn_addWord;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_done;
    private javax.swing.JComboBox cBox_languageOne;
    private javax.swing.JComboBox cBox_languageTwo;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table_glossaryList;
    private javax.swing.JTextField txtfield_listname;
    private javax.swing.JTextField txtfield_word1;
    private javax.swing.JTextField txtfield_word2;
    // End of variables declaration//GEN-END:variables
}
