/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client;

/**
 *
 * @author pierrezarebski
 */
public class MainFrameGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public MainFrameGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        menu_tBtn1 = new javax.swing.JToggleButton();
        menu_tBtn2 = new javax.swing.JToggleButton();
        menu_tBtn3 = new javax.swing.JToggleButton();
        menu_tBtn4 = new javax.swing.JToggleButton();
        cardLayoutPanel = new javax.swing.JPanel();
        panel_quiz = new javax.swing.JPanel();
        quiz_label_language = new javax.swing.JLabel();
        quiz_cBox_lang1 = new javax.swing.JComboBox();
        quiz_cBox_lang2 = new javax.swing.JComboBox();
        quiz_label_list = new javax.swing.JLabel();
        quiz_cBox_myLists = new javax.swing.JComboBox();
        quiz_cBox_otherLists = new javax.swing.JComboBox();
        quiz_label_answerLanguage = new javax.swing.JLabel();
        quiz_tBtn_lang1 = new javax.swing.JToggleButton();
        quiz_tBtn_langMix = new javax.swing.JToggleButton();
        quiz_tBtn_lang2 = new javax.swing.JToggleButton();
        quiz_tBtn_freetext = new javax.swing.JToggleButton();
        quiz_tBtn_3alt = new javax.swing.JToggleButton();
        quiz_label_difficulty = new javax.swing.JLabel();
        quiz_btn_start = new javax.swing.JButton();
        panel_quiz_3alt = new javax.swing.JPanel();
        quizAlt_progressBar = new javax.swing.JProgressBar();
        quizAlt_label_word = new javax.swing.JLabel();
        quizAlt_tBtn_word1 = new javax.swing.JToggleButton();
        quizAlt_tBtn_word2 = new javax.swing.JToggleButton();
        quizAlt_tBtn_word3 = new javax.swing.JToggleButton();
        quizAlt_label_correct = new javax.swing.JLabel();
        panel_quiz_freetext = new javax.swing.JPanel();
        quizText_progressBar = new javax.swing.JProgressBar();
        quizText_label_word = new javax.swing.JLabel();
        quizText_txtField = new javax.swing.JTextField();
        quizText_label_correct = new javax.swing.JLabel();
        panel_newList = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        newList_btn_add = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panel_stats = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panel_settings = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 362));

        menuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        menu_tBtn1.setText("Quiz");
        menu_tBtn1.setMaximumSize(new java.awt.Dimension(125, 29));
        menu_tBtn1.setMinimumSize(new java.awt.Dimension(125, 29));
        menu_tBtn1.setPreferredSize(new java.awt.Dimension(125, 29));
        menu_tBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tBtn1ActionPerformed(evt);
            }
        });

        menu_tBtn2.setText("Ny Gloslista");
        menu_tBtn2.setMaximumSize(new java.awt.Dimension(125, 29));
        menu_tBtn2.setMinimumSize(new java.awt.Dimension(125, 29));
        menu_tBtn2.setPreferredSize(new java.awt.Dimension(125, 29));
        menu_tBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tBtn2ActionPerformed(evt);
            }
        });

        menu_tBtn3.setText("Statistik");
        menu_tBtn3.setMaximumSize(new java.awt.Dimension(125, 29));
        menu_tBtn3.setMinimumSize(new java.awt.Dimension(125, 29));
        menu_tBtn3.setPreferredSize(new java.awt.Dimension(125, 29));
        menu_tBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tBtn3ActionPerformed(evt);
            }
        });

        menu_tBtn4.setText("Inställningar");
        menu_tBtn4.setMaximumSize(new java.awt.Dimension(125, 29));
        menu_tBtn4.setMinimumSize(new java.awt.Dimension(125, 29));
        menu_tBtn4.setPreferredSize(new java.awt.Dimension(125, 29));
        menu_tBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tBtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(menu_tBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(menu_tBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(menu_tBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(menu_tBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menu_tBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(menu_tBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menu_tBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menu_tBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        cardLayoutPanel.setLayout(new java.awt.CardLayout());

        panel_quiz.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_quiz.setName("panel_quiz"); // NOI18N

        quiz_label_language.setText("Välj de språk du vill öva på");

        quiz_cBox_lang1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Språk 1-", "Svenska", "Engelska" }));
        quiz_cBox_lang1.setMinimumSize(new java.awt.Dimension(150, 27));
        quiz_cBox_lang1.setPreferredSize(new java.awt.Dimension(150, 27));

        quiz_cBox_lang2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Språk 2-", "Svenska", "Engelska" }));
        quiz_cBox_lang2.setMinimumSize(new java.awt.Dimension(150, 27));
        quiz_cBox_lang2.setPreferredSize(new java.awt.Dimension(150, 27));

        quiz_label_list.setText("Välj en gloslista");

        quiz_cBox_myLists.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Andra listor-", "Lista1", "Lista2" }));
        quiz_cBox_myLists.setMinimumSize(new java.awt.Dimension(150, 27));
        quiz_cBox_myLists.setPreferredSize(new java.awt.Dimension(150, 27));

        quiz_cBox_otherLists.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Mina listor-", "Lista1", "Lista2" }));
        quiz_cBox_otherLists.setToolTipText("");
        quiz_cBox_otherLists.setMinimumSize(new java.awt.Dimension(150, 27));
        quiz_cBox_otherLists.setPreferredSize(new java.awt.Dimension(150, 27));

        quiz_label_answerLanguage.setText("Vilket språk vill du svara i?");

        quiz_tBtn_lang1.setText("Språk 1");
        quiz_tBtn_lang1.setMaximumSize(new java.awt.Dimension(100, 29));
        quiz_tBtn_lang1.setMinimumSize(new java.awt.Dimension(100, 29));
        quiz_tBtn_lang1.setPreferredSize(new java.awt.Dimension(100, 29));
        quiz_tBtn_lang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiz_tBtn_lang1ActionPerformed(evt);
            }
        });

        quiz_tBtn_langMix.setText("Blanda");
        quiz_tBtn_langMix.setMaximumSize(new java.awt.Dimension(100, 29));
        quiz_tBtn_langMix.setMinimumSize(new java.awt.Dimension(100, 29));
        quiz_tBtn_langMix.setPreferredSize(new java.awt.Dimension(100, 29));
        quiz_tBtn_langMix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiz_tBtn_langMixActionPerformed(evt);
            }
        });

        quiz_tBtn_lang2.setText("Språk 2");
        quiz_tBtn_lang2.setMaximumSize(new java.awt.Dimension(100, 29));
        quiz_tBtn_lang2.setMinimumSize(new java.awt.Dimension(100, 29));
        quiz_tBtn_lang2.setPreferredSize(new java.awt.Dimension(100, 29));
        quiz_tBtn_lang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiz_tBtn_lang2ActionPerformed(evt);
            }
        });

        quiz_tBtn_freetext.setText("Fritext");
        quiz_tBtn_freetext.setMaximumSize(new java.awt.Dimension(100, 29));
        quiz_tBtn_freetext.setMinimumSize(new java.awt.Dimension(100, 29));
        quiz_tBtn_freetext.setPreferredSize(new java.awt.Dimension(100, 29));
        quiz_tBtn_freetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiz_tBtn_freetextActionPerformed(evt);
            }
        });

        quiz_tBtn_3alt.setText("3 Alternativ");
        quiz_tBtn_3alt.setMaximumSize(new java.awt.Dimension(100, 29));
        quiz_tBtn_3alt.setMinimumSize(new java.awt.Dimension(100, 29));
        quiz_tBtn_3alt.setPreferredSize(new java.awt.Dimension(100, 29));
        quiz_tBtn_3alt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiz_tBtn_3altActionPerformed(evt);
            }
        });

        quiz_label_difficulty.setText("Vilket språk vill du svara i?");

        quiz_btn_start.setText("Starta Quizen!");
        quiz_btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quiz_btn_startActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_quizLayout = new javax.swing.GroupLayout(panel_quiz);
        panel_quiz.setLayout(panel_quizLayout);
        panel_quizLayout.setHorizontalGroup(
            panel_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_quizLayout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(panel_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quiz_label_difficulty)
                    .addGroup(panel_quizLayout.createSequentialGroup()
                        .addComponent(quiz_tBtn_lang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quiz_tBtn_langMix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quiz_tBtn_lang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(quiz_label_answerLanguage)
                    .addGroup(panel_quizLayout.createSequentialGroup()
                        .addComponent(quiz_cBox_otherLists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(quiz_cBox_myLists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(quiz_label_list)
                    .addComponent(quiz_label_language)
                    .addGroup(panel_quizLayout.createSequentialGroup()
                        .addComponent(quiz_cBox_lang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(quiz_cBox_lang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_quizLayout.createSequentialGroup()
                        .addComponent(quiz_tBtn_3alt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quiz_tBtn_freetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(quiz_btn_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        panel_quizLayout.setVerticalGroup(
            panel_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_quizLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quiz_label_language)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quiz_cBox_lang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quiz_cBox_lang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quiz_label_list)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quiz_cBox_otherLists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quiz_cBox_myLists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quiz_label_answerLanguage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quiz_tBtn_lang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quiz_tBtn_langMix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quiz_tBtn_lang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quiz_label_difficulty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_quizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quiz_tBtn_3alt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quiz_tBtn_freetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quiz_btn_start, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardLayoutPanel.add(panel_quiz, "card1");

        quizAlt_progressBar.setMinimumSize(new java.awt.Dimension(300, 20));
        quizAlt_progressBar.setPreferredSize(new java.awt.Dimension(300, 20));

        quizAlt_label_word.setFont(new java.awt.Font("Myriad Pro", 0, 48)); // NOI18N
        quizAlt_label_word.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizAlt_label_word.setText("GLOSORD");

        quizAlt_tBtn_word1.setText("Ord1");

        quizAlt_tBtn_word2.setText("Ord2");

        quizAlt_tBtn_word3.setText("Ord3");

        quizAlt_label_correct.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        quizAlt_label_correct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizAlt_label_correct.setText("Antal rätt:");

        javax.swing.GroupLayout panel_quiz_3altLayout = new javax.swing.GroupLayout(panel_quiz_3alt);
        panel_quiz_3alt.setLayout(panel_quiz_3altLayout);
        panel_quiz_3altLayout.setHorizontalGroup(
            panel_quiz_3altLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_quiz_3altLayout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addGroup(panel_quiz_3altLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_quiz_3altLayout.createSequentialGroup()
                        .addComponent(quizAlt_tBtn_word1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quizAlt_tBtn_word2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quizAlt_tBtn_word3))
                    .addComponent(quizAlt_progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quizAlt_label_word, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quizAlt_label_correct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        panel_quiz_3altLayout.setVerticalGroup(
            panel_quiz_3altLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_quiz_3altLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizAlt_progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(quizAlt_label_word)
                .addGap(33, 33, 33)
                .addGroup(panel_quiz_3altLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quizAlt_tBtn_word1)
                    .addComponent(quizAlt_tBtn_word2)
                    .addComponent(quizAlt_tBtn_word3))
                .addGap(36, 36, 36)
                .addComponent(quizAlt_label_correct)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        cardLayoutPanel.add(panel_quiz_3alt, "card6");

        quizText_progressBar.setMinimumSize(new java.awt.Dimension(300, 20));
        quizText_progressBar.setPreferredSize(new java.awt.Dimension(300, 20));

        quizText_label_word.setFont(new java.awt.Font("Myriad Pro", 0, 48)); // NOI18N
        quizText_label_word.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizText_label_word.setText("GLOSORD");

        quizText_txtField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        quizText_label_correct.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        quizText_label_correct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quizText_label_correct.setText("Antal rätt:");

        javax.swing.GroupLayout panel_quiz_freetextLayout = new javax.swing.GroupLayout(panel_quiz_freetext);
        panel_quiz_freetext.setLayout(panel_quiz_freetextLayout);
        panel_quiz_freetextLayout.setHorizontalGroup(
            panel_quiz_freetextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_quiz_freetextLayout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addGroup(panel_quiz_freetextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quizText_progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quizText_label_word, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quizText_txtField)
                    .addComponent(quizText_label_correct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        panel_quiz_freetextLayout.setVerticalGroup(
            panel_quiz_freetextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_quiz_freetextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizText_progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(quizText_label_word)
                .addGap(33, 33, 33)
                .addComponent(quizText_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(quizText_label_correct)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        cardLayoutPanel.add(panel_quiz_freetext, "card7");

        panel_newList.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_newList.setName("panel_newList"); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Språk 1-", "Svenska", "Engelska" }));
        jComboBox1.setMinimumSize(new java.awt.Dimension(150, 27));
        jComboBox1.setPreferredSize(new java.awt.Dimension(150, 27));
        jComboBox1.setSize(new java.awt.Dimension(150, 27));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Språk 2-", "Svenska", "Engelska" }));
        jComboBox2.setMinimumSize(new java.awt.Dimension(150, 27));
        jComboBox2.setPreferredSize(new java.awt.Dimension(150, 27));
        jComboBox2.setSize(new java.awt.Dimension(150, 27));

        newList_btn_add.setText("Lägg till");
        newList_btn_add.setMaximumSize(new java.awt.Dimension(100, 29));
        newList_btn_add.setMinimumSize(new java.awt.Dimension(100, 29));
        newList_btn_add.setPreferredSize(new java.awt.Dimension(100, 29));

        jTextField3.setEditable(false);
        jTextField3.setText("Hej");

        jTextField4.setEditable(false);
        jTextField4.setText("Hi");

        jButton6.setText("E");
        jButton6.setMaximumSize(new java.awt.Dimension(40, 29));
        jButton6.setMinimumSize(new java.awt.Dimension(40, 29));
        jButton6.setPreferredSize(new java.awt.Dimension(40, 29));
        jButton6.setSize(new java.awt.Dimension(40, 29));

        jButton7.setText("X");
        jButton7.setMaximumSize(new java.awt.Dimension(40, 29));
        jButton7.setMinimumSize(new java.awt.Dimension(40, 29));
        jButton7.setPreferredSize(new java.awt.Dimension(40, 29));
        jButton7.setSize(new java.awt.Dimension(40, 29));

        jButton1.setText("Avbryt");

        jButton2.setText("Klar");

        javax.swing.GroupLayout panel_newListLayout = new javax.swing.GroupLayout(panel_newList);
        panel_newList.setLayout(panel_newListLayout);
        panel_newListLayout.setHorizontalGroup(
            panel_newListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_newListLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(panel_newListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3)
                    .addComponent(jTextField2)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(panel_newListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_newListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panel_newListLayout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1))
                        .addGroup(panel_newListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panel_newListLayout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_newListLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(newList_btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        panel_newListLayout.setVerticalGroup(
            panel_newListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_newListLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel_newListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panel_newListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newList_btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panel_newListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(panel_newListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        cardLayoutPanel.add(panel_newList, "card2");

        panel_stats.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_stats.setName("panel_stats"); // NOI18N

        jLabel3.setText("Statistik");

        javax.swing.GroupLayout panel_statsLayout = new javax.swing.GroupLayout(panel_stats);
        panel_stats.setLayout(panel_statsLayout);
        panel_statsLayout.setHorizontalGroup(
            panel_statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
            .addGroup(panel_statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_statsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_statsLayout.setVerticalGroup(
            panel_statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
            .addGroup(panel_statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_statsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        cardLayoutPanel.add(panel_stats, "card3");

        panel_settings.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_settings.setName("panel_settings"); // NOI18N

        jLabel4.setText("Inställningar");

        javax.swing.GroupLayout panel_settingsLayout = new javax.swing.GroupLayout(panel_settings);
        panel_settings.setLayout(panel_settingsLayout);
        panel_settingsLayout.setHorizontalGroup(
            panel_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
            .addGroup(panel_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_settingsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_settingsLayout.setVerticalGroup(
            panel_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
            .addGroup(panel_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_settingsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        cardLayoutPanel.add(panel_settings, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cardLayoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 309, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(cardLayoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_tBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tBtn2ActionPerformed
        changePanel(panel_newList);
        
        menu_tBtn1.setSelected(false);
        menu_tBtn3.setSelected(false);
        menu_tBtn4.setSelected(false);
    }//GEN-LAST:event_menu_tBtn2ActionPerformed

    private void menu_tBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tBtn1ActionPerformed
        changePanel(panel_quiz);
        
        menu_tBtn2.setSelected(false);
        menu_tBtn3.setSelected(false);
        menu_tBtn4.setSelected(false);
    }//GEN-LAST:event_menu_tBtn1ActionPerformed

    private void menu_tBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tBtn3ActionPerformed
        changePanel(panel_stats);
        
        menu_tBtn1.setSelected(false);
        menu_tBtn2.setSelected(false);
        menu_tBtn4.setSelected(false);
    }//GEN-LAST:event_menu_tBtn3ActionPerformed

    private void menu_tBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tBtn4ActionPerformed
        changePanel(panel_settings);
        
        menu_tBtn1.setSelected(false);
        menu_tBtn2.setSelected(false);
        menu_tBtn3.setSelected(false);
    }//GEN-LAST:event_menu_tBtn4ActionPerformed

    private void quiz_btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiz_btn_startActionPerformed
        if (quiz_tBtn_3alt.isSelected()) {
            changePanel(panel_quiz_3alt);
        } else if (quiz_tBtn_freetext.isSelected()){
            changePanel(panel_quiz_freetext);
        }
    }//GEN-LAST:event_quiz_btn_startActionPerformed

    private void quiz_tBtn_lang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiz_tBtn_lang1ActionPerformed
        quiz_tBtn_langMix.setSelected(false);
        quiz_tBtn_lang2.setSelected(false);
    }//GEN-LAST:event_quiz_tBtn_lang1ActionPerformed

    private void quiz_tBtn_langMixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiz_tBtn_langMixActionPerformed
        quiz_tBtn_lang1.setSelected(false);
        quiz_tBtn_lang2.setSelected(false);
    }//GEN-LAST:event_quiz_tBtn_langMixActionPerformed

    private void quiz_tBtn_lang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiz_tBtn_lang2ActionPerformed
        quiz_tBtn_lang1.setSelected(false);
        quiz_tBtn_langMix.setSelected(false);
    }//GEN-LAST:event_quiz_tBtn_lang2ActionPerformed

    private void quiz_tBtn_3altActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiz_tBtn_3altActionPerformed
        quiz_tBtn_freetext.setSelected(false);
    }//GEN-LAST:event_quiz_tBtn_3altActionPerformed

    private void quiz_tBtn_freetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quiz_tBtn_freetextActionPerformed
        quiz_tBtn_3alt.setSelected(false);
    }//GEN-LAST:event_quiz_tBtn_freetextActionPerformed

    private void changePanel(javax.swing.JPanel panel) {
        cardLayoutPanel.removeAll();
        cardLayoutPanel.add(panel);
        cardLayoutPanel.repaint();
        cardLayoutPanel.revalidate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardLayoutPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JToggleButton menu_tBtn1;
    private javax.swing.JToggleButton menu_tBtn2;
    private javax.swing.JToggleButton menu_tBtn3;
    private javax.swing.JToggleButton menu_tBtn4;
    private javax.swing.JButton newList_btn_add;
    private javax.swing.JPanel panel_newList;
    private javax.swing.JPanel panel_quiz;
    private javax.swing.JPanel panel_quiz_3alt;
    private javax.swing.JPanel panel_quiz_freetext;
    private javax.swing.JPanel panel_settings;
    private javax.swing.JPanel panel_stats;
    private javax.swing.JLabel quizAlt_label_correct;
    private javax.swing.JLabel quizAlt_label_word;
    private javax.swing.JProgressBar quizAlt_progressBar;
    private javax.swing.JToggleButton quizAlt_tBtn_word1;
    private javax.swing.JToggleButton quizAlt_tBtn_word2;
    private javax.swing.JToggleButton quizAlt_tBtn_word3;
    private javax.swing.JLabel quizText_label_correct;
    private javax.swing.JLabel quizText_label_word;
    private javax.swing.JProgressBar quizText_progressBar;
    private javax.swing.JTextField quizText_txtField;
    private javax.swing.JButton quiz_btn_start;
    private javax.swing.JComboBox quiz_cBox_lang1;
    private javax.swing.JComboBox quiz_cBox_lang2;
    private javax.swing.JComboBox quiz_cBox_myLists;
    private javax.swing.JComboBox quiz_cBox_otherLists;
    private javax.swing.JLabel quiz_label_answerLanguage;
    private javax.swing.JLabel quiz_label_difficulty;
    private javax.swing.JLabel quiz_label_language;
    private javax.swing.JLabel quiz_label_list;
    private javax.swing.JToggleButton quiz_tBtn_3alt;
    private javax.swing.JToggleButton quiz_tBtn_freetext;
    private javax.swing.JToggleButton quiz_tBtn_lang1;
    private javax.swing.JToggleButton quiz_tBtn_lang2;
    private javax.swing.JToggleButton quiz_tBtn_langMix;
    // End of variables declaration//GEN-END:variables
}
