package client2.login;

import client2.MainFrame;
import client2.MainFrameListener;
import client2.student.NewUserFrame;

/**
 *
 * @author pierrezarebski
 */
public class LoginFrameOld extends javax.swing.JFrame implements LoginFrameSetter {
    
    LoginListener listener;
    MainFrameListener mfListener;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrameOld() {
        initComponents();
    }
    
    public void setLoginOk(){
         mfListener.mainFrameCreate();
         setVisible(false);
        // TODO skicka mainframe till game via setter
    }
    
    public void wrongUser(String message){
        javax.swing.JOptionPane.showMessageDialog(this, message);
    }
    
    public void setLoginListener(LoginListener listener){
        this.listener = listener;
    }
            
    public void setMainFrameListener(MainFrameListener mfListener) {
        this.mfListener = mfListener;
    }
            
            
        //TODO handle duplicate user, Show message dialog
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtfield_username = new javax.swing.JTextField();
        txtfield_password = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        btn_newUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(320, 240));
        setMinimumSize(new java.awt.Dimension(320, 240));
        setPreferredSize(new java.awt.Dimension(320, 240));

        txtfield_username.setForeground(new java.awt.Color(153, 153, 153));
        txtfield_username.setText("Username...");
        txtfield_username.setPreferredSize(new java.awt.Dimension(200, 28));
        txtfield_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfield_usernameMouseClicked(evt);
            }
        });

        txtfield_password.setForeground(new java.awt.Color(153, 153, 153));
        txtfield_password.setText("Password...");
        txtfield_password.setPreferredSize(new java.awt.Dimension(200, 28));
        txtfield_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfield_passwordMouseClicked(evt);
            }
        });

        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        btn_newUser.setFont(new java.awt.Font("Myriad Pro", 0, 10)); // NOI18N
        btn_newUser.setForeground(new java.awt.Color(0, 0, 255));
        btn_newUser.setText("<HTML>Registrera dig</HTML>");
        btn_newUser.setBorder(null);
        btn_newUser.setBorderPainted(false);
        btn_newUser.setContentAreaFilled(false);
        btn_newUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_newUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_newUserMouseExited(evt);
            }
        });
        btn_newUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtfield_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_newUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_login)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(txtfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfield_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_login)
                    .addComponent(btn_newUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_newUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newUserActionPerformed
       mfListener.newUserFrameCreate();
       setVisible(false);
    }//GEN-LAST:event_btn_newUserActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        listener.loginBtnPressed(txtfield_username.getText(),txtfield_password.getText());
        setVisible(false);
    }//GEN-LAST:event_btn_loginActionPerformed

    private void txtfield_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfield_usernameMouseClicked
        txtfield_username.setText(null);
    }//GEN-LAST:event_txtfield_usernameMouseClicked

    private void txtfield_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfield_passwordMouseClicked
        txtfield_password.setText(null);
    }//GEN-LAST:event_txtfield_passwordMouseClicked

    private void btn_newUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newUserMouseEntered
        btn_newUser.setText("<HTML><U>Registrera dig</U></HTML>");
    }//GEN-LAST:event_btn_newUserMouseEntered

    private void btn_newUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newUserMouseExited
        btn_newUser.setText("<HTML>Registrera dig</HTML>");
    }//GEN-LAST:event_btn_newUserMouseExited

    /**
     * @param args the command line arguments
     */
    public  void initialize() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrameOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrameOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrameOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrameOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_newUser;
    private javax.swing.JTextField txtfield_password;
    private javax.swing.JTextField txtfield_username;
    // End of variables declaration//GEN-END:variables
}
