/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client2;

/**
 *
 * @author pierrezarebski
 */
public class GlossaryView extends javax.swing.JPanel {

    private GlossaryListener listener;
    /**
     * Creates new panel GlossaryView
     */
    public GlossaryView() {
        initComponents();
    }

    public GlossaryView(GlossaryListener listener){
        initComponents();
        this.listener = listener;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        table_glossaryList = new javax.swing.JTable();
        btn_cancel = new javax.swing.JButton();
        btn_done = new javax.swing.JButton();
        btn_addWord = new javax.swing.JButton();
        btn_addLang = new javax.swing.JButton();
        txtfield_word2 = new javax.swing.JTextField();
        txtfield_word1 = new javax.swing.JTextField();
        cBox_languageTwo = new javax.swing.JComboBox();
        cBox_languageOne = new javax.swing.JComboBox();

        table_glossaryList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Svenska", "Språk 2"
            }
        ));
        table_glossaryList.setColumnSelectionAllowed(true);
        table_glossaryList.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(table_glossaryList);
        table_glossaryList.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btn_cancel.setText("Avbryt");

        btn_done.setText("Klar");

        btn_addWord.setText("Lägg till");
        btn_addWord.setMaximumSize(new java.awt.Dimension(100, 29));
        btn_addWord.setMinimumSize(new java.awt.Dimension(100, 29));
        btn_addWord.setPreferredSize(new java.awt.Dimension(100, 29));

        btn_addLang.setText("Lägg till");
        btn_addLang.setMaximumSize(new java.awt.Dimension(100, 29));
        btn_addLang.setMinimumSize(new java.awt.Dimension(100, 29));
        btn_addLang.setPreferredSize(new java.awt.Dimension(100, 29));

        cBox_languageTwo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Språk 2-", "Engelska" }));
        cBox_languageTwo.setMinimumSize(new java.awt.Dimension(150, 27));
        cBox_languageTwo.setPreferredSize(new java.awt.Dimension(150, 27));

        cBox_languageOne.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Svenska" }));
        cBox_languageOne.setMinimumSize(new java.awt.Dimension(150, 27));
        cBox_languageOne.setPreferredSize(new java.awt.Dimension(150, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfield_word1)
                            .addComponent(cBox_languageOne, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cBox_languageTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_addLang, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_done)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_cancel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtfield_word2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_addWord, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBox_languageOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBox_languageTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfield_word2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfield_word1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel)
                    .addComponent(btn_done))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addLang;
    private javax.swing.JButton btn_addWord;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_done;
    private javax.swing.JComboBox cBox_languageOne;
    private javax.swing.JComboBox cBox_languageTwo;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table_glossaryList;
    private javax.swing.JTextField txtfield_word1;
    private javax.swing.JTextField txtfield_word2;
    // End of variables declaration//GEN-END:variables
}
