package client2;

/**
 *
 * @author pierrezarebski
 */
public class MainFrame extends javax.swing.JFrame {

    //private MainFrameListener listener;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    /*public MainFrame(MainFrameListener listener){
        initComponents();
        this.listener = listener;
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        menu_tBtn1 = new javax.swing.JToggleButton();
        menu_tBtn2 = new javax.swing.JToggleButton();
        menu_tBtn3 = new javax.swing.JToggleButton();
        menu_tBtn4 = new javax.swing.JToggleButton();
        cardLayoutPanel = new javax.swing.JPanel();
        startPanel = new client2.StartView();
        quizPanel = new client2.QuizView();
        quizAlternativesPanel = new client2.QuizAlternativesView();
        quizTextPanel = new client2.QuizTextView();
        glossaryPanel = new client2.GlossaryView();
        statisticsPanel = new client2.StatisticsView();
        settingsPanel = new client2.SettingsView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 362));

        menuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        menu_tBtn1.setText("Quiz");
        menu_tBtn1.setMaximumSize(new java.awt.Dimension(125, 29));
        menu_tBtn1.setMinimumSize(new java.awt.Dimension(125, 29));
        menu_tBtn1.setPreferredSize(new java.awt.Dimension(125, 29));
        menu_tBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tBtn1ActionPerformed(evt);
            }
        });

        menu_tBtn2.setText("Ny Gloslista");
        menu_tBtn2.setMaximumSize(new java.awt.Dimension(125, 29));
        menu_tBtn2.setMinimumSize(new java.awt.Dimension(125, 29));
        menu_tBtn2.setPreferredSize(new java.awt.Dimension(125, 29));
        menu_tBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tBtn2ActionPerformed(evt);
            }
        });

        menu_tBtn3.setText("Statistik");
        menu_tBtn3.setMaximumSize(new java.awt.Dimension(125, 29));
        menu_tBtn3.setMinimumSize(new java.awt.Dimension(125, 29));
        menu_tBtn3.setPreferredSize(new java.awt.Dimension(125, 29));
        menu_tBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tBtn3ActionPerformed(evt);
            }
        });

        menu_tBtn4.setText("Inställningar");
        menu_tBtn4.setMaximumSize(new java.awt.Dimension(125, 29));
        menu_tBtn4.setMinimumSize(new java.awt.Dimension(125, 29));
        menu_tBtn4.setPreferredSize(new java.awt.Dimension(125, 29));
        menu_tBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tBtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(menu_tBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(menu_tBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(menu_tBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(menu_tBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menu_tBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(menu_tBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menu_tBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(menu_tBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardLayoutPanel.setLayout(new java.awt.CardLayout());
        cardLayoutPanel.add(startPanel, "card8");
        cardLayoutPanel.add(quizPanel, "card7");
        cardLayoutPanel.add(quizAlternativesPanel, "card7");
        cardLayoutPanel.add(quizTextPanel, "card8");
        cardLayoutPanel.add(glossaryPanel, "card7");
        cardLayoutPanel.add(statisticsPanel, "card7");
        cardLayoutPanel.add(settingsPanel, "card8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cardLayoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 309, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(cardLayoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_tBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tBtn2ActionPerformed
        changePanel(glossaryPanel);
        
        menu_tBtn1.setSelected(false);
        menu_tBtn3.setSelected(false);
        menu_tBtn4.setSelected(false);
    }//GEN-LAST:event_menu_tBtn2ActionPerformed

    private void menu_tBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tBtn1ActionPerformed
        changePanel(quizPanel);
        
        menu_tBtn2.setSelected(false);
        menu_tBtn3.setSelected(false);
        menu_tBtn4.setSelected(false);
    }//GEN-LAST:event_menu_tBtn1ActionPerformed

    private void menu_tBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tBtn3ActionPerformed
        changePanel(statisticsPanel);
        
        menu_tBtn1.setSelected(false);
        menu_tBtn2.setSelected(false);
        menu_tBtn4.setSelected(false);
    }//GEN-LAST:event_menu_tBtn3ActionPerformed

    private void menu_tBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tBtn4ActionPerformed
        changePanel(settingsPanel);
        
        menu_tBtn1.setSelected(false);
        menu_tBtn2.setSelected(false);
        menu_tBtn3.setSelected(false);
    }//GEN-LAST:event_menu_tBtn4ActionPerformed

    private void changePanel(javax.swing.JPanel panel) {
        cardLayoutPanel.removeAll();
        cardLayoutPanel.add(panel);
        cardLayoutPanel.repaint();
        cardLayoutPanel.revalidate();
    }
    
    public void initialize() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainFrameView().setVisible(true);
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardLayoutPanel;
    private client2.GlossaryView glossaryPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JToggleButton menu_tBtn1;
    private javax.swing.JToggleButton menu_tBtn2;
    private javax.swing.JToggleButton menu_tBtn3;
    private javax.swing.JToggleButton menu_tBtn4;
    private client2.QuizAlternativesView quizAlternativesPanel;
    private client2.QuizView quizPanel;
    private client2.QuizTextView quizTextPanel;
    private client2.SettingsView settingsPanel;
    private client2.StartView startPanel;
    private client2.StatisticsView statisticsPanel;
    // End of variables declaration//GEN-END:variables
}
