/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client2;

/**
 *
 * @author pierrezarebski
 */
public class QuizView extends javax.swing.JPanel {

    private QuizViewListener listener;
    /**
     * Creates new form QuizView
     */
    public QuizView() {
        initComponents();
    }
    
    public QuizView(QuizViewListener listener){
        initComponents();
        this.listener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_language = new javax.swing.JLabel();
        label_glossaryList = new javax.swing.JLabel();
        label_responseLanguage = new javax.swing.JLabel();
        label_difficulty = new javax.swing.JLabel();
        cBox_otherLists = new javax.swing.JComboBox();
        cBox_userLists = new javax.swing.JComboBox();
        cBox_languageOne = new javax.swing.JComboBox();
        cBox_languageTwo = new javax.swing.JComboBox();
        toggleBtn_languageOne = new javax.swing.JToggleButton();
        toggleBtn_languageMix = new javax.swing.JToggleButton();
        toggleBtn_languageTwo = new javax.swing.JToggleButton();
        toggleBtn_textQuiz = new javax.swing.JToggleButton();
        toggleBtn_alternativesQuiz = new javax.swing.JToggleButton();
        btn_startQuiz = new javax.swing.JButton();

        label_language.setText("Välj de språk du vill öva på");

        label_glossaryList.setText("Välj en gloslista");

        label_responseLanguage.setText("Vilket språk vill du svara i?");

        label_difficulty.setText("Vilket språk vill du svara i?");

        cBox_otherLists.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Andra listor-", "Lista1", "Lista2" }));
        cBox_otherLists.setMinimumSize(new java.awt.Dimension(150, 27));
        cBox_otherLists.setPreferredSize(new java.awt.Dimension(150, 27));

        cBox_userLists.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Mina listor-", "Lista1", "Lista2" }));
        cBox_userLists.setToolTipText("");
        cBox_userLists.setMinimumSize(new java.awt.Dimension(150, 27));
        cBox_userLists.setPreferredSize(new java.awt.Dimension(150, 27));

        cBox_languageOne.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Språk 1-", "Svenska", "Engelska" }));
        cBox_languageOne.setMinimumSize(new java.awt.Dimension(150, 27));
        cBox_languageOne.setPreferredSize(new java.awt.Dimension(150, 27));

        cBox_languageTwo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Språk 2-", "Svenska", "Engelska" }));
        cBox_languageTwo.setMinimumSize(new java.awt.Dimension(150, 27));
        cBox_languageTwo.setPreferredSize(new java.awt.Dimension(150, 27));

        toggleBtn_languageOne.setText("Språk 1");
        toggleBtn_languageOne.setMaximumSize(new java.awt.Dimension(100, 29));
        toggleBtn_languageOne.setMinimumSize(new java.awt.Dimension(100, 29));
        toggleBtn_languageOne.setPreferredSize(new java.awt.Dimension(100, 29));
        toggleBtn_languageOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleBtn_languageOneActionPerformed(evt);
            }
        });

        toggleBtn_languageMix.setText("Blanda");
        toggleBtn_languageMix.setMaximumSize(new java.awt.Dimension(100, 29));
        toggleBtn_languageMix.setMinimumSize(new java.awt.Dimension(100, 29));
        toggleBtn_languageMix.setPreferredSize(new java.awt.Dimension(100, 29));
        toggleBtn_languageMix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleBtn_languageMixActionPerformed(evt);
            }
        });

        toggleBtn_languageTwo.setText("Språk 2");
        toggleBtn_languageTwo.setMaximumSize(new java.awt.Dimension(100, 29));
        toggleBtn_languageTwo.setMinimumSize(new java.awt.Dimension(100, 29));
        toggleBtn_languageTwo.setPreferredSize(new java.awt.Dimension(100, 29));
        toggleBtn_languageTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleBtn_languageTwoActionPerformed(evt);
            }
        });

        toggleBtn_textQuiz.setText("Fritext");
        toggleBtn_textQuiz.setMaximumSize(new java.awt.Dimension(100, 29));
        toggleBtn_textQuiz.setMinimumSize(new java.awt.Dimension(100, 29));
        toggleBtn_textQuiz.setPreferredSize(new java.awt.Dimension(100, 29));
        toggleBtn_textQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleBtn_textQuizActionPerformed(evt);
            }
        });

        toggleBtn_alternativesQuiz.setText("3 Alternativ");
        toggleBtn_alternativesQuiz.setMaximumSize(new java.awt.Dimension(100, 29));
        toggleBtn_alternativesQuiz.setMinimumSize(new java.awt.Dimension(100, 29));
        toggleBtn_alternativesQuiz.setPreferredSize(new java.awt.Dimension(100, 29));
        toggleBtn_alternativesQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleBtn_alternativesQuizActionPerformed(evt);
            }
        });

        btn_startQuiz.setText("Starta Quizen!");
        btn_startQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startQuizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_difficulty)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toggleBtn_languageOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleBtn_languageMix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleBtn_languageTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_responseLanguage)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cBox_userLists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cBox_otherLists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_glossaryList)
                    .addComponent(label_language)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cBox_languageOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cBox_languageTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toggleBtn_alternativesQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleBtn_textQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_startQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_language)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBox_languageOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBox_languageTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_glossaryList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBox_userLists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBox_otherLists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_responseLanguage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleBtn_languageOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggleBtn_languageMix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggleBtn_languageTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_difficulty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleBtn_alternativesQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggleBtn_textQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_startQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

   /*
    Här ska väl listernern anropas för att ta in två parametrar lang1 och lang2
    */
    private void toggleBtn_languageOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleBtn_languageOneActionPerformed
        toggleBtn_languageMix.setSelected(false);
        toggleBtn_languageTwo.setSelected(false);
    }//GEN-LAST:event_toggleBtn_languageOneActionPerformed

    private void toggleBtn_languageMixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleBtn_languageMixActionPerformed
        toggleBtn_languageOne.setSelected(false);
        toggleBtn_languageTwo.setSelected(false);
    }//GEN-LAST:event_toggleBtn_languageMixActionPerformed

    private void toggleBtn_languageTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleBtn_languageTwoActionPerformed
        toggleBtn_languageOne.setSelected(false);
        toggleBtn_languageMix.setSelected(false);
    }//GEN-LAST:event_toggleBtn_languageTwoActionPerformed

    private void toggleBtn_textQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleBtn_textQuizActionPerformed
        toggleBtn_alternativesQuiz.setSelected(false);
    }//GEN-LAST:event_toggleBtn_textQuizActionPerformed

    private void toggleBtn_alternativesQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleBtn_alternativesQuizActionPerformed
        toggleBtn_textQuiz.setSelected(false);
    }//GEN-LAST:event_toggleBtn_alternativesQuizActionPerformed

    private void btn_startQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startQuizActionPerformed
        /*if (quiz_tBtn_3alt.isSelected()) {
            changePanel(mainFrame.panel_quiz_3alt);
        } else if (quiz_tBtn_freetext.isSelected()){
            changePanel(panel_quiz_freetext);
        }*/
    }//GEN-LAST:event_btn_startQuizActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_startQuiz;
    private javax.swing.JComboBox cBox_languageOne;
    private javax.swing.JComboBox cBox_languageTwo;
    private javax.swing.JComboBox cBox_otherLists;
    private javax.swing.JComboBox cBox_userLists;
    private javax.swing.JLabel label_difficulty;
    private javax.swing.JLabel label_glossaryList;
    private javax.swing.JLabel label_language;
    private javax.swing.JLabel label_responseLanguage;
    private javax.swing.JToggleButton toggleBtn_alternativesQuiz;
    private javax.swing.JToggleButton toggleBtn_languageMix;
    private javax.swing.JToggleButton toggleBtn_languageOne;
    private javax.swing.JToggleButton toggleBtn_languageTwo;
    private javax.swing.JToggleButton toggleBtn_textQuiz;
    // End of variables declaration//GEN-END:variables
}
