/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client2;

/**
 *
 * @author pierrezarebski
 */
public class QuizAlternativesView extends javax.swing.JPanel {

    private QuizAlternativesListener listener;
    /**
     * Creates new form QuizAlternativesView
     */
    public QuizAlternativesView() {
        initComponents();
    }
    
    public QuizAlternativesView(QuizAlternativesListener listener) {
        initComponents();
        this.listener = listener;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        label_activeWord = new javax.swing.JLabel();
        label_correctAnswers = new javax.swing.JLabel();
        toggleBtn_wordOne = new javax.swing.JToggleButton();
        toggleBtn_wordTwo = new javax.swing.JToggleButton();
        toggleBtn_wordThree = new javax.swing.JToggleButton();

        progressBar.setMinimumSize(new java.awt.Dimension(300, 20));
        progressBar.setPreferredSize(new java.awt.Dimension(300, 20));

        label_activeWord.setFont(new java.awt.Font("Myriad Pro", 0, 48)); // NOI18N
        label_activeWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_activeWord.setText("GLOSORD");

        label_correctAnswers.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        label_correctAnswers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_correctAnswers.setText("Antal rätt:");

        toggleBtn_wordOne.setText("Ord1");

        toggleBtn_wordTwo.setText("Ord2");

        toggleBtn_wordThree.setText("Ord3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toggleBtn_wordOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toggleBtn_wordTwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toggleBtn_wordThree))
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_activeWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_correctAnswers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(label_activeWord)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleBtn_wordOne)
                    .addComponent(toggleBtn_wordTwo)
                    .addComponent(toggleBtn_wordThree))
                .addGap(36, 36, 36)
                .addComponent(label_correctAnswers)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_activeWord;
    private javax.swing.JLabel label_correctAnswers;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JToggleButton toggleBtn_wordOne;
    private javax.swing.JToggleButton toggleBtn_wordThree;
    private javax.swing.JToggleButton toggleBtn_wordTwo;
    // End of variables declaration//GEN-END:variables
}
