/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package client2;

/**
 *
 * @author pierrezarebski
 */
public class QuizAlternativesView extends javax.swing.JPanel implements QuizAlternativesViewSetter {

    private QuizAlternativesListener listener;
    /**
     * Creates new form QuizAlternativesView
     */
    public QuizAlternativesView() {
        initComponents();
    }
    
    public void setQuizAlternativesViewListener(QuizAlternativesListener listener){
           this.listener = listener;
    }
    
    public void setIsCorrect(int numberOfCorrectAnswers){
        
        progressBar.setValue(progressBar.getValue() + 1);
        System.out.println("Correct!");
        label_correctAnswers.setText("" + numberOfCorrectAnswers);
    }
    
    public void setIsInCorrect(){
        System.out.println("Incorrect");
    }
    
    public void setWord(String word){
         label_activeWord.setText(word);
    }
    
    public void setAlt1(String word){
        toggleBtn_wordOne.setText(word);
    }
    
    public void setAlt2(String word){
        toggleBtn_wordTwo.setText(word);
    }
    
    public void setAlt3(String word){
        toggleBtn_wordThree.setText(word);
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        label_activeWord = new javax.swing.JLabel();
        label_correctAnswers = new javax.swing.JLabel();
        toggleBtn_wordOne = new javax.swing.JToggleButton();
        toggleBtn_wordTwo = new javax.swing.JToggleButton();
        toggleBtn_wordThree = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        progressBar.setMinimumSize(new java.awt.Dimension(300, 20));
        progressBar.setPreferredSize(new java.awt.Dimension(300, 20));

        label_activeWord.setFont(new java.awt.Font("Myriad Pro", 0, 48)); // NOI18N
        label_activeWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_activeWord.setText("GLOSORD");

        label_correctAnswers.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        label_correctAnswers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_correctAnswers.setText("Antal rätt:");

        toggleBtn_wordOne.setText("Ord1");
        toggleBtn_wordOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleBtn_wordOneActionPerformed(evt);
            }
        });

        toggleBtn_wordTwo.setText("Ord2");
        toggleBtn_wordTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleBtn_wordTwoActionPerformed(evt);
            }
        });

        toggleBtn_wordThree.setText("Ord3");
        toggleBtn_wordThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleBtn_wordThreeActionPerformed(evt);
            }
        });

        jButton1.setText("Nästa ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toggleBtn_wordOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toggleBtn_wordTwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toggleBtn_wordThree))
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_activeWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_correctAnswers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(label_activeWord)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggleBtn_wordOne)
                    .addComponent(toggleBtn_wordTwo)
                    .addComponent(toggleBtn_wordThree))
                .addGap(18, 18, 18)
                .addComponent(label_correctAnswers)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        listener.nextWord();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void toggleBtn_wordOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleBtn_wordOneActionPerformed
        listener.wordOneBtnPressed(toggleBtn_wordOne.getText());
    }//GEN-LAST:event_toggleBtn_wordOneActionPerformed

    private void toggleBtn_wordTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleBtn_wordTwoActionPerformed
         listener.wordTwoBtnPressed(toggleBtn_wordTwo.getText());
    }//GEN-LAST:event_toggleBtn_wordTwoActionPerformed

    private void toggleBtn_wordThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleBtn_wordThreeActionPerformed
         listener.wordThreeBtnPressed(toggleBtn_wordThree.getText());
    }//GEN-LAST:event_toggleBtn_wordThreeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel label_activeWord;
    private javax.swing.JLabel label_correctAnswers;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JToggleButton toggleBtn_wordOne;
    private javax.swing.JToggleButton toggleBtn_wordThree;
    private javax.swing.JToggleButton toggleBtn_wordTwo;
    // End of variables declaration//GEN-END:variables
}
